# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-24 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Brand', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('ProductCode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('CostPrice', models.FloatField()),
                ('SellingPrice', models.FloatField()),
                ('Quantity', models.IntegerField(default=0)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='Variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Variant'),
        ),
    ]
